### ISSUE TITLE
Challege에서의 결과가 Practice에서도 보입니다.

### ISSUE THREAD

**Issue by conggooksi** [c9u11/bulls-and-cows#2]
안녕하세요 c9u11님. Bulls and Cows 재밌게 하고 있습니다.

그런데! Challege를 마치고 결과가 뜨고 있을 때 Practice로 넘어가니, Practice를 하는 도중에 결과 창이 뜨네요.

**Comment by c9u11** [comment]
https://github.com/c9u11/bulls-and-cows/commit/0599d365c72860a404203f808ea9d15ea8a1c99e

수정하였습니다. 버그 리포트 감사합니다.
